### ISSUE TITLE
Question: Why are all actions performed in callbacks given to register_before_send?

### ISSUE THREAD

**Issue by Francesco-Lanciana** [ejpcmac/expected#5]
Hey I'm currently learning Elixir/Phoenix and was reading your library as learning material. I'm curious why all actions (e.g. update_login) are performed in callbacks given to register_before_send? Why not perform that work in the plug that set the action (e.g. authenticate)? 

Is it to enable users of the library to write middleware that can alter the action before it is performed? Or was there some other reason?

Really interested to hear your answer :)

**Comment by ejpcmac** [comment]
Hi Francesco,

I’ve discussed this subject in the announcement article on my blog [1],
you may be interested in reading it.

Otherwise, I’m not maintaining actively this library at the time, due to
a lack of bandwidth. There is at least one issue with it I foresee:
updating the session variables when they cache DB variable that can be
updated elsewhere. This is to be addressed before this library can
really be used to build a decent application I think. I’ve thought of
callbacks somewhere, but maybe it’s overkill.

[1] https://ejpcmac.net/blog/persistent-logins-in-elixir-with-expected/#some-more-technical-details

**Comment by Francesco-Lanciana** [comment]
Thanks for pointing me to the blog post, that really helped. I'm currently writing my own code to accomplish something similar (sessions + refresh tokens for a sliding window indefinite login) so it's interesting to see what you ran into. I'm just using the cookie as the session store so I think that simplifies things a little bit. 

I'm not quite sure by what you meant regarding the forseeable issue, what did you mean by "cache DB variable that can be updated elsewhere"? What's being cached? And why would they be updated from elsewhere?

**Comment by ejpcmac** [comment]
> I'm not quite sure by what you meant regarding the forseeable issue,
> what did you mean by "cache DB variable that can be updated
> elsewhere"? What's being cached? And why would they be updated from
> elsewhere?

I’m thinking about the current_user specifically. It is used for
authentication, then kept in the session so you can use it in your
application for authorisation. The problem is when you want to update
the role for a user with a running expected session: you need to update
both the database and the session itself.

**Comment by Francesco-Lanciana** [comment]
Couldn't you just keep the current user on the assigns field? So the idea is the session contains the user ID and you have some middleware to get the user ID and return the users details from your DB (roles, ect). This way as soon as the role is updated it will be reflected when authorising a request.
